vdl_tilgangsstyring_profile:
  target: "{{ env_var('DBT_TARGET', 'transformer') }}"
  outputs:
    transformer:
      type: "snowflake"
      account: "wx23413.europe-west4.gcp"
      # User/password auth
      user: "{{ env_var('SRV_USR') }}"
      password: "{{ env_var('SRV_PWD') }}"
      role: "tilgangsstyring_admin"
      database: "{{ env_var('tilgangsstyring') }}"
      warehouse: "tilgangsstyring_app"
      schema: "PUBLIC"
      threads: 8
      client_session_keep_alive: False
    dev_sso:
      type: snowflake
      account: "wx23413.europe-west4.gcp"
      user: "{{ env_var('DBT_USR') }}"
      role: "tilgangsstyring_admin"
      # SSO config
      authenticator: externalbrowser
      database: "{{ env_var('tilgangsstyring') }}"
      warehouse: "tilgangsstyring_app"
      schema: "PUBLIC"
      threads: 8
      client_session_keep_alive: False
      reuse_connections: True
    snowflake_users:
      type: snowflake
      account: "wx23413.europe-west4.gcp"
      user: "{{ env_var('DBT_USR') }}"
      role: "accountadmin"
      # SSO config
      authenticator: externalbrowser
      database: "snowflake_user"
      warehouse: "tilgangsstyring_app"
      schema: "account_usage"
      threads: 8
      client_session_keep_alive: False
      reuse_connections: True