vdl_tilgangsstyring_profile:
  target: "{{ env_var('DBT_TARGET', 'dev_sso') }}"
  outputs:
    dev_sso:
      type: snowflake
      account: "wx23413.europe-west4.gcp"
      user: "{{ env_var('DBT_USR') }}"
      role: "tilgangsstyring_developer"
      # SSO config
      authenticator: externalbrowser
      database: "tilgangsstyring"
      warehouse: "tilgangsstyring_app"
      schema: "app"
      threads: 8
      client_session_keep_alive: False
      reuse_connections: True