version: "1.0"

# Databases
databases:
  - tilgangsstyring:
      shared: no
      owner: sysadmin
      schemas:
        - app
        - policies 
  - snowflake_users:
      shared: no
      owner: accountadmin
      schemas:
        - account_usage

# Roles
roles:
  - snowflake_users_reader:
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - snowflake_users
          write:
            - snowflake_users
        schemas:
          read:
            - snowflake_users.account_usage
          write:
            - snowflake_users.account_usage
        tables:
          read: 
            - snowflake_users.account_usage.*
      owner: useradmin

  - tilgangsstyring_user:
      member_of:
        - snowflake_users_reader
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - tilgangsstyring
          write:
            - tilgangsstyring
        schemas:
          read:
            - tilgangsstyring.app
            - tilgangsstyring.policies 
          write:
            - tilgangsstyring.app
            - tilgangsstyring.policies 
        tables:
          read:
            - tilgangsstyring.app.*
            - tilgangsstyring.policies.*
          write:
            - tilgangsstyring.app.*
            - tilgangsstyring.policies.*
      owner: useradmin

  - tilgangsstyring_developer:
      member_of:
        - tilgangsstyring_user
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - tilgangsstyring
          write:
            - tilgangsstyring
        schemas:
          read:
            - tilgangsstyring.app
            - tilgangsstyring.policies 
          write:
            - tilgangsstyring.app
            - tilgangsstyring.policies  
      owns:
        tables:
          - tilgangsstyring.app.*
          - tilgangsstyring.policies.*
      owner: useradmin    
  - tilgangsstyring_reporter:
      privileges:
        databases:
          read:
            - tilgangsstyring
          write:
            - tilgangsstyring
        schemas:
          read:
            - tilgangsstyring.policies 
        tables:
          read:
            - tilgangsstyring.policies.*
      owner: useradmin


warehouses:
  - tilgangsstyring_app:
      size: x-small
      owner: sysadmin
