version: "1.0"

# Databases
databases:
  - tilgangsstyring:
      shared: no
      owner: sysadmin
      schemas:
        - app
  - snowflake_users:
      shared: no
      owner: accountadmin
      schemas:
        - account_usage

# Roles
roles:
  - snowflake_users_reader:
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - snowflake_users
          write:
            - snowflake_users
        schemas:
          read:
            - snowflake_users.account_usage
          write:
            - snowflake_users.account_usage
        tables:
          read: 
            - snowflake_users.account_usage.*
      owner: useradmin

  - tilgangsstyring_admin:
      member_of:
        - regnskap_reporter
        - snowflake_users_reader
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - tilgangsstyring
          write:
            - tilgangsstyring
        schemas:
          read:
            - tilgangsstyring.app
          write:
            - tilgangsstyring.app
        tables:
          read:
            - tilgangsstyring.app.*
          write:
            - tilgangsstyring.app.*
      owns:
        tables:
          - tilgangsstyring.app.*
      owner: useradmin

warehouses:
  - tilgangsstyring_app:
      size: x-small
      owner: sysadmin
