version: "1.0"

# Databases
databases:
  - tilgangsstyring:
      shared: no
      owner: sysadmin
      schemas:
        - app
        - policies 
  - snowflake_users:
      shared: no
      owner: accountadmin
      schemas:
        - account_usage
  - tilgangsstyring__raw:
      shared: no
      owner: sysadmin
      schemas:
        - oebs
        - csv

# Roles
roles:
  - tilgangsstyring_loader:
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - tilgangsstyring__raw
          write:
            - tilgangsstyring__raw
        schemas:
          read:
            - tilgangsstyring__raw.oebs
            - tilgangsstyring__raw.csv
          write:
            - tilgangsstyring__raw.oebs
            - tilgangsstyring__raw.csv
        tables:
          read: 
            - tilgangsstyring__raw.oebs.*
            - tilgangsstyring__raw.csv.*
          write:
            - tilgangsstyring__raw.csv.*
      owner: useradmin

  - snowflake_users_reader:
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - snowflake_users
          write:
            - snowflake_users
        schemas:
          read:
            - snowflake_users.account_usage
          write:
            - snowflake_users.account_usage
        tables:
          read: 
            - snowflake_users.account_usage.*
      owner: useradmin

  - tilgangsstyring_user:
      member_of:
        - snowflake_users_reader
        - tilgangsstyring_loader
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - tilgangsstyring
          write:
            - tilgangsstyring
        schemas:
          read:
            - tilgangsstyring.app
            - tilgangsstyring.policies 
          write:
            - tilgangsstyring.app
            - tilgangsstyring.policies 
        tables:
          read:
            - tilgangsstyring.app.*
            - tilgangsstyring.policies.*
          write:
            - tilgangsstyring.app.*
            - tilgangsstyring.policies.*
      owner: useradmin

  - tilgangsstyring_developer:
      member_of:
        - tilgangsstyring_user
      warehouses:
        - tilgangsstyring_app
      privileges:
        databases:
          read:
            - tilgangsstyring
            - tilgangsstyring__raw
          write:
            - tilgangsstyring
        schemas:
          read:
            - tilgangsstyring.app
            - tilgangsstyring.policies 
            - tilgangsstyring__raw.csv
            - tilgangsstyring__raw.oebs
          write:
            - tilgangsstyring.app
            - tilgangsstyring.policies  
        tables:
          read: 
            - tilgangsstyring__raw.csv.*
            - tilgangsstyring__raw.oebs.*
      owns:
        tables:
          - tilgangsstyring.app.*
          - tilgangsstyring.policies.*
      owner: useradmin    
  - tilgangsstyring_reporter:
      privileges:
        databases:
          read:
            - tilgangsstyring
          write:
            - tilgangsstyring
        schemas:
          read:
            - tilgangsstyring.policies 
        tables:
          read:
            - tilgangsstyring.policies.*
      owner: useradmin


warehouses:
  - tilgangsstyring_app:
      size: x-small
      owner: sysadmin
